config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  RATING = [0, 1, 2, 3, 4, 5]
  # validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: RATING }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      # make a seperate request to go to the show page
      redirect_to restaurant_path(@restaurant)
    else
      # show the new.html.erb (but with the @restaurant we just tried to create)
      render 'new', status: :unprocessable_entity # 422
    end
  end

  

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other # redirect
  end


  private

  # strong params
  def restaurant_params
    # whitelists the attributes a user can give in the form (for security)
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private
  
    def review_params
      params.require(:review).permit(:content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
  <%= simple_form_for @restaurant do |f| %>
  <%= f.input :name%>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit 'Submit', class: 'btn btn-primary mt-2' %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <div class="d-flex justify-content-between">
    <h1>Hello Restaurant Man</h1>
    <%= link_to "Add Restaurant", new_restaurant_path, class: "d-flex btn btn-primary align-bottom" %>
  </div>
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-sm">
        <div class="card-trip m-3">
          <img src="https://loremflickr.com/320/240/soccer/all?lock=<%= restaurant.id %>" />
          <div class="card-trip-infos">
            <div>
              <%= link_to restaurant_path(restaurant), class: "text-decoration-none " do %>
                <h2><strong><%= restaurant.name %></strong></h2>
              <% end %>
              <p><%= restaurant.category %></p>
            </div>
            <div class="card-trip-pricing">
              <h3><%= restaurant.address %></h3>
              <br>
              <%# <h3>restaurant.phone_number</h3> %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container w-50">
  <h1>Form Bros</h1>
  <%= render "restaurants/form" %>
  <%= link_to "Back", "/restaurants", class: "btn btn-dark mt-3" %>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-3 ">
  <div class="d-flex justify-content-between row vertical-align">
    <div class="col-sm">
      <div class="card-trip m-3">
        <img src="https://loremflickr.com/320/240/soccer/all?lock=<%= @restaurant.id %>" />
        <div class="card-trip-infos">
          <h2><%= @restaurant.name %></h2>
          <p><%= @restaurant.category %></p>
          <div>
            <h3><%= @restaurant.address %></h3>
          </div>
        </div>
      </div>
    </div>
    <div>
      <ul class="list-unstyled">
        <% if @restaurant.reviews.any? %>
          <h2>Reviews</h2>
          <% @restaurant.reviews.each do |review| %>
            <li>
              <%= review.content %>
              <%= link_to 'X', review_path(review), data: { turbo_method: :delete, turbo_confirm: 'Delete review?' } %>
            </li>
          <% end %>
        <% else %>
          <li>No reviews yet</li>
        <% end %>
      </ul>
      <%= link_to "Home", restaurants_path, class: "btn btn-dark"  %>
      <%= link_to "Review", new_restaurant_review_path(@restaurant), class: "btn btn-info" %>
      <%= link_to 'Delete', restaurant_path(@restaurant), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: 'Delete restaurant?' } %>
    </div>
  </div>

app/views/reviews/new.html.erb
<div class="container w-50">
  <h1>Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit "Submit", class: "btn btn-success" %>
  <% end %>
  <%= link_to "Home", restaurants_path, class: "btn btn-dark mt-3"  %>
</div>